language: c

services:
  - docker
    
before_install:
  - docker pull anlun/opam-ci
  - docker run -it -d --name build -v $(pwd):/usr/share/imm anlun/opam-ci

cache:
  apt: true
  directories:
  - $HOME/.opam
env:
  global:
  - NJOBS=5
  - OPAMYES=true
  - OCAMLC="4.10.0"
  matrix:
  - COQC="8.9.1"
matrix:
  fast_finish: true
os:
    - linux

install:
- docker exec build opam init
- docker exec build eval $(opam config env)
- docker exec build opam config var root
- docker exec build opam update
- docker exec build opam install coq.${COQC} 
- docker exec build coqc -v
- docker exec build opam remote add coq-released https://coq.inria.fr/opam/released
- docker exec build opam remote add coq-promising-local -k git https://github.com/snu-sf/promising-opam-coq-archive
- docker exec build opam remote add coq-weakmemory-local -k git https://github.com/weakmemory/local-coq-opam-archive
- docker exec build opam install coq-hahn coq-promising-lib

script:
- set -e
- echo 'Building IMM...';
  echo -en 'travis_fold:start:IMM.build';
  make -j -k;
  echo -en 'travis_fold:end:IMM.build'
